#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env_rmlui = env.Clone()

module_obj = []

excluded = []


thirdparty_sources = (
    Glob("thirdparty/RmlUi/Source/Core/*.cpp")
    + Glob("thirdparty/RmlUi/Source/Debugger/*.cpp")            # Form controls, data grid, tabs, etc.
    + Glob("thirdparty/RmlUi/Source/Core/Layout/*.cpp")            # Form controls, data grid, tabs, etc.
    + Glob("thirdparty/RmlUi/Source/Core/Elements/*.cpp")            # Form controls, data grid, tabs, etc.
    + Glob("thirdparty/RmlUi/Source/Core/FontEngineDefault/*.cpp")  # Built-in FreeType font engine
)

freetype_include_path = "#thirdparty/freetype/include"
env_rmlui.Prepend(CPPPATH=[freetype_include_path])

env_rmlui_third_party = env_rmlui.Clone()
env_rmlui_third_party.disable_warnings()
thirdparty_obj = []
env_rmlui_third_party.add_source_files(thirdparty_obj, thirdparty_sources)

SConscript("backend/shaders/SCsub")

env.modules_sources += thirdparty_obj

env_rmlui.Prepend(CPPPATH=["thirdparty/RmlUi/Include"])
sources = (Glob("*.cpp") + Glob("backend/*.cpp") + Glob("extra/*.cpp"))

env_rmlui.add_source_files(module_obj, sources)
env.modules_sources += module_obj
